### PR TITLE
Bring topiary back and run it by default

### LINKED ISSUE #158: Add topiary to the pipeline
Given the name/purpose of this pipeline ("Personalized cancer **epitope discovery** and **peptide vaccine prediction** pipeline"), I think we should run topiary by default in addition to vaxrank and include the list of predicted neoepitopes in the results.

### PR DESCRIPTION
**Pull request by armish**
Depends on https://github.com/hammerlab/biokepi/pull/432.
Resolves #158.

### CODE REVIEW

**Comment by ihodes** [comment]
LGTM pending comments on the biokepi PR!

**Review by smondet — APPROVED** [review]
LGTM².

Waiting on Topiary PR & release, and then Biokepi PR :)

**Comment by hammer** [comment]
@iskandr are we actively developing topiary? I feel like recent action has been in vaxrank.

cf. https://github.com/hammerlab/cohorts/issues/163 and https://github.com/hammerlab/vaxrank/issues/31

**Comment by iskandr** [comment]
@hammer Some random folks outside the lab use it and I'm keeping Topiary current with other upstream changes to e.g. mhctools. So it's used but not currently necessary for PGV.

**Pull request merged**
